name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mike
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-minify-plugin
          pip install mkdocs-redirects
          pip install mkdocs-awesome-pages-plugin
          pip install pymdown-extensions
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Deploy documentation
        working-directory: ./docs
        run: |
          mike deploy --push --update-aliases latest
          mike set-default --push latest 