name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cairo-dev libcairo2-dev libfreetype6-dev
      
      - name: Install Python dependencies
        run: |
          pip install -r docs/requirements.txt
      
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Deploy documentation
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          mkdocs gh-deploy --force
          git push origin gh-pages
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
      
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site/
          retention-days: 30 